FROM python:3.8.13-slim
COPY requirements.txt .
RUN apt-get update && apt-get install -y vim
RUN pip install -r requirements.txt
COPY serve_llama2.py /serve/serve_llama2.py
WORKDIR /serve
ENTRYPOINT [ "/bin//bash" ]